winget install --id Google.Chrome -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id Telegram.TelegramDesktop -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id Bitwarden.Bitwarden -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id Obsidian.Obsidian -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id SlackTechnologies.Slack -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id Zoom.Zoom -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id Skillbrains.Lightshot -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id 7zip.7zip -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id ALCPU.CoreTemp -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id Kitware.CMake -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id Python.Python.3.12 -h -e --accept-source-agreements --accept-package-agreements --force --source winget
winget install --id OpenJS.NodeJS.LTS -h -e --accept-source-agreements --accept-package-agreements --force --source winget
